// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWzkfqEj-xFRyFg34RGJ9oQYJJyhhEnDo',
    appId: '1:339125530903:web:143b68c5888cb20182c752',
    messagingSenderId: '339125530903',
    projectId: 'masjid-a4e50',
    authDomain: 'masjid-a4e50.firebaseapp.com',
    storageBucket: 'masjid-a4e50.firebasestorage.app',
    measurementId: 'G-HEG8TCESXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhlIyOe_4fF5B1nA6U5LPNdj6MkjhRCSQ',
    appId: '1:339125530903:android:9475d3e4f0ae0c5b82c752',
    messagingSenderId: '339125530903',
    projectId: 'masjid-a4e50',
    storageBucket: 'masjid-a4e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJv-Rif7IrrPTb9ajtTpuHpRNAYgb-Bk',
    appId: '1:339125530903:ios:31967ef17f995a2682c752',
    messagingSenderId: '339125530903',
    projectId: 'masjid-a4e50',
    storageBucket: 'masjid-a4e50.firebasestorage.app',
    androidClientId:
        '339125530903-h69ll655bhor3889ctvqoumuokg02bk0.apps.googleusercontent.com',
    iosClientId:
        '339125530903-d3dnr1u2mbnc1lcqgdrs0n9k0ia5isrd.apps.googleusercontent.com',
    iosBundleId: 'com.admin.masjidadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJv-Rif7IrrPTb9ajtTpuHpRNAYgb-Bk',
    appId: '1:339125530903:ios:31967ef17f995a2682c752',
    messagingSenderId: '339125530903',
    projectId: 'masjid-a4e50',
    storageBucket: 'masjid-a4e50.firebasestorage.app',
    androidClientId:
        '339125530903-h69ll655bhor3889ctvqoumuokg02bk0.apps.googleusercontent.com',
    iosClientId:
        '339125530903-d3dnr1u2mbnc1lcqgdrs0n9k0ia5isrd.apps.googleusercontent.com',
    iosBundleId: 'com.admin.masjidadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWzkfqEj-xFRyFg34RGJ9oQYJJyhhEnDo',
    appId: '1:339125530903:web:143b68c5888cb20182c752',
    messagingSenderId: '339125530903',
    projectId: 'masjid-a4e50',
    authDomain: 'masjid-a4e50.firebaseapp.com',
    storageBucket: 'masjid-a4e50.firebasestorage.app',
    measurementId: 'G-HEG8TCESXP',
  );
}
